# Generated by Django 3.2.3 on 2021-06-19 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='carts',
        ),
    ]
