# Generated by Django 3.2.3 on 2021-06-21 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_orders'),
    ]

    operations = [
        migrations.DeleteModel(
            name='orders',
        ),
    ]
