# Generated by Django 3.2.3 on 2021-07-04 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
        ('adminapp', '0007_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='orders1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(upload_to='orders')),
                ('product', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('pri', models.FloatField()),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.products')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.register')),
            ],
        ),
        migrations.AlterField(
            model_name='address',
            name='oid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.orders1'),
        ),
        migrations.DeleteModel(
            name='orders',
        ),
    ]
