# Generated by Django 3.2.3 on 2021-07-06 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0009_auto_20210706_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders2',
            name='oid',
        ),
    ]
