# Generated by Django 3.2.3 on 2021-07-06 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0010_remove_orders2_oid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='orders2',
        ),
    ]
