# Generated by Django 3.2.3 on 2021-07-06 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
        ('adminapp', '0012_orders2'),
    ]

    operations = [
        migrations.CreateModel(
            name='paym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardname', models.CharField(max_length=100)),
                ('cardnumber', models.CharField(max_length=100)),
                ('subtotal', models.FloatField()),
                ('oid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.orders2')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.products')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.register')),
            ],
        ),
        migrations.DeleteModel(
            name='pay',
        ),
    ]
