# Generated by Django 3.2.3 on 2021-07-06 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0013_auto_20210706_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paym',
            name='pid',
        ),
    ]
