# Generated by Django 3.2.3 on 2021-07-07 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0014_remove_paym_pid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paym',
            name='oid',
        ),
    ]
