# Generated by Django 3.2.3 on 2021-07-07 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0016_auto_20210707_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders3',
            name='pid',
        ),
        migrations.RemoveField(
            model_name='orders3',
            name='uid',
        ),
        migrations.RemoveField(
            model_name='paym',
            name='uid',
        ),
        migrations.DeleteModel(
            name='orders1',
        ),
        migrations.DeleteModel(
            name='orders3',
        ),
        migrations.DeleteModel(
            name='paym',
        ),
    ]
